### PR TITLE
show faculty header

### PR DESCRIPTION
**Pull request by wwwApp**

### CODE REVIEW

**Comment by jervo** [comment]
You will need to upload your changes to the dev site to confirm functionality before I accept pull request.

**Comment by wwwApp** [comment]
@jervo you should be able to check it on jervo.com/status!

**Comment by jervo** [comment]
- Did you test in chrome browser?
- Align "Faculty" in Header with "Name" in first column.
200430-Chrome
200430-Safari

**Comment by wwwApp** [comment]
@jervo 

yes! i just tested on other browsers - FF and Safari, and it seems to work!
alignment is updated as well :-)

**Comment by wwwApp** [comment]
@jervo auto-scroll should be triggered if you have more than 21 rows of faculty info (which takes up the full height of the table) or it can be tested by adding `.scroll-table` to `div.faculty-table`

**Pull request merged**
